### ISSUE TITLE
Warning messages and output

### ISSUE THREAD

**Issue by woodoo46** [Illumina/ExpansionHunter#2]
Hi, there,

We have tried the program on our interested regions, we had some warning messages:

**has low weighed purity score of 0.5**

We are wondering what this means?

Also, you probably have mentioned somewhere, I may have missed the explanation. The output from the program: 

Reasign flanking to spanning

how can we use this information? 

Thanks.

**Comment by egor-dolzhenko** [comment]
Thanks for your questions and for trying out the program!

Expansion Hunter outputs the weighted purity warning when it checks repeat-specification files for potential problems. The program expects that the `TargetRegion` consists of an integer number of copies of the `RepeatUnit`. To check this, Expansion Hunter calculates weighted purity score between the target region and the "perfect" repeat consisting of an appropriate number of repeat units. The low-score warnings are not necessarily a sign of a problem since there is a natural variability in the repeat sequence of some repeats (e.g. AGG interruptions in CGG repeats; see below). However, it is a good idea to confirm that the repeat region and the repeat unit are specified correctly.

For example the sequence of the repeat in FMR1 gene is 
```
$samtools faidx hg19.fa chrX:146993569-146993628
  >chrX:146993569-146993628
  cggcggcggcggcggcggcggcggcggcggaggcggcggcggcggcggcggcggcggcgg
```
which is not a a pure stretch of CGGs (the repeat unit) hence the weighted purity is less than 1.

Now to your second question. Often the sequence immediately flanking the repeat is very similar to the repeat itself. Because of this, occasionally we get reads for which it is impossible to tell if they are flanking or spanning. Such reads are assigned to repeat alleles estimated from spanning reads at the very end (this is when the message you observed is output). These ambiguously aligning reads do not contribute to the number of supporting reads that the program outputs for each allele. They only show up in the log files. So, this information is meant only as a QC metric (many reassignments are indicative of a difficult repeat whose flanks have very high identity to the repeat itself).

PS: I would be happy to assist you in producing repeat-specification files for repeats in regions you are interested in. Feel free to email me: edolzhenko@illumina.com.

--Egor
