### ISSUE TITLE
Running with an unexpected Error

### ISSUE THREAD

**Issue by Bowei-xiao** [Illumina/ExpansionHunter#48]
Hi,
   First I'd like to express my thanks to this project as it seems to fit in what I'm doing right now. I'm looking for a region where the reference itself has highly repetitive sequence and I'm not sure how many portion of the repeats does my reads have.
   I'm running on this on hg38 aligned files and I was running into problems. The variant-catalog file didn't contain the region that I am interested in so it gives error like this:

2019-03-01T18:21:45,[Could not recover the mate of E00387:228:HN7TFCCXY:2:1205:22912:64245/1]

When I created my own JSON script, it popped up an error 

2019-03-01T17:51:07,[Definition of variant ID=XXX;classification=SmallVariant/Swap;ReferenceLocus=(4):***-***;optionalRefNode=None is inconsistent]

where I'm not sure what it means exactly. The "ReferenceRegion" I provided is 'chr5:486858-486869' but I don't think it's properly parsed to the program based on this errror. Could you help me explaining a bit of this error about what it means to be 'inconsistent'?

Thank you very much
Bowei

**Comment by egor-dolzhenko** [comment]
Hi Bowei,

Thank you for using the program and sorry about the cryptic error message. The program produced an error because it found an inconsistency in the variant definition. (`(4)` in the error message refers to the index of chr5).

Could you please share the definition of the region? If you prefer to not share it publicly on GitHub, feel free to send it to me by email (edolzhenko@illumina.com).

And the warning message "Could not recover the mate of ..." is produced when the program cannot find a mate of a read aligned close to one of the target regions. This could happen due to a number of reasons. Might it be possible to extract alignment records for "E00387:228:HN7TFCCXY:2:1205:22912:64245" reads from your BAM file?

Best wishes,
Egor
