### ISSUE TITLE
(AAAAG|AAGGG)*

### ISSUE THREAD

**Issue by dnil** [Illumina/ExpansionHunter#62]
I suspect there would be quite a bit of interest to have an option for switched repeat units. Have you had a look at this already? Other suggestions for good workarounds for RFC1? I'm currently just using (AAGGG)*... Cheers!

**Comment by egor-dolzhenko** [comment]
Great suggestion. Our long/medium-term goal is to allow regular expressions like (RepeatUnit1|RepeatUnit1|...)*. Though this will require a good amount of work since the corresponding sequence graph could get quite complex.

However, this particular repeat could be defined by (AARRG)*, using a degenerate base symbol R that matches to A or G.
