### ISSUE TITLE
"Invalid contig name X" using example data

### ISSUE THREAD

**Issue by leekaiinthesky** [Illumina/ExpansionHunter#96]
Hi all, thanks so much for providing your program. I'm looking forward to running it. I just gave it a shot using the provided example data and got this error. I've tried it a few different ways to no avail.

Input:
`./build/ExpansionHunter --reads example/input/variants.bam --reference example/input/reference.fa --variant-catalog variant_catalog/grch37/variant_catalog.json --output-prefix example`

Output:
`2020-01-28T00:29:27,[Starting Expansion Hunter v3.2.0]
2020-01-28T00:29:27,[Workflow parameter object is initialized with HeuristicParameters(regionExtensionLength=1000, qualityCutoffForGoodBaseCall=20, skipUnaligned=true, alignerType=dag-aligner, kmerLenForAlignment=14, paddingLength=10, seedAffixTrimLength=14)]
2020-01-28T00:29:27,[Analyzing sample variants]
2020-01-28T00:29:27,[Initializing reference example/input/reference.fa]
[fai_load] build FASTA index.
2020-01-28T00:29:27,[Loading variant catalog from disk variant_catalog/hg19/variant_catalog.json]
2020-01-28T00:29:27,[Invalid contig name chrX]`

I also tried switching to `variant_catalog/grch37/variant_catalog.json`, producing a slightly different error message (`Invalid contig name X` instead of `Invalid contig name chrX`) and also tried providing a full reference genome rather than the example one (which didn't change anything). I haven't tried using my own bams because I don't feel that should change anything.

Now wondering whether I'm not actually supposed to be using the example variant catalogs. Any feedback would be helpful.

Thank you!
Lee-kai

**Comment by egor-dolzhenko** [comment]
Hi Lee-kai,

Thanks for the question and sorry about the trouble with the example data. Could you please try pointing the program to the variant catalog from the example folder (`example/input/variants.json`)?

```bash
./build/ExpansionHunter \
  --reads example/input/variants.bam \
  --reference example/input/reference.fa \
  --variant-catalog example/input/variants.json \
  --output-prefix example
```

To keep the example files small, all example data was simulated. The catalog file `variant_catalog/grch37/variant_catalog.json` is made for a full-size human genome assembly. During the catalog-loading stage, the program tried to extract a piece of sequence from "chrX" and since the simulated reference does not have this contig, the program errored out.

Also, are you building the program from the master branch? If yes, could you please try the [latest release](https://github.com/Illumina/ExpansionHunter/releases) (either build from source or use a pre-compiled binary)? We are in the middle of a major update and it's possible that the code on the master and develop branches may not be fully functional at the moment.

Please let me know if this solves the issue or if you have any other questions.

Best wishes,
Egor

**Comment by leekaiinthesky** [comment]
Hi Egor, thanks for the quick reply! Yes, when I use `example/input/variants.json`, I have no problem.

But using the full variant catalog even with a whole-genome reference still produces the same error.

I am now using the pre-compiled v3.2.0, and I am trying a standard whole-genome reference, human_g1k_v37.fasta.gz + human_g1k_v37.fasta.fai from: http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/. I get the same error "Invalid contig name X".

I may try reverting to release v3.1.2 next to see if that changes anything. Thank you for your attention!

**Comment by eberle** [comment]
Hi Lee-kai, 

Are you still using the same bam file but just a different reference file? I think that could be the problem because you need a reads file that was aligned to the full genome. 

Cheers,
Mike

**Comment by egor-dolzhenko** [comment]
This sounds good! The program expects that the provided reference is the same as the one used for read alignment, so using your own bam file should help.

**Comment by egor-dolzhenko** [comment]
@leekaiinthesky Lee-kai, were you able to run the program? Please let us know if our suggestions did not help.

**Comment by leekaiinthesky** [comment]
Hi @egor-dolzhenko and @eberle. I've now tried switching to my own bam file on the latest release, and the program runs properly. Will close the issue now. Thanks very much for your attention!
